### ISSUE TITLE
MCTS: adjustable temperature for random exploration in top most level

### ISSUE THREAD

**Issue by barakugav** [poja/RL#12]

**Comment by poja** [comment]
Are you sure?
From what I understand, we don't need this because of the UCT solution for exploration-exploitation. 
I looked at the AlphaGo Zero paper, they have a temperature parameter but they use it only at the **decision** point, not for the MCTS-selection phase. In the selection phase they use something similar to UCT (but with an additional NN heuristic)
![image](https://user-images.githubusercontent.com/4618146/158032882-ba1c84eb-522c-4409-9850-c55a4e04644b.png)
.

**Comment by barakugav** [comment]
correct

**Comment by barakugav** [comment]
Action is now chosen with softmax with a fixed temperature of 2.
5025a7f8cd77b236d4e72dffbd208023af2666df

Need to make it adjustable

**Comment by barakugav** [comment]
Add support for changing temperature after number of steps

**Comment by barakugav** [comment]
From AlphaGo paper:
"For the first 30 moves of each game, the temperature is set to τ=1; this
selects moves proportionally to their visit count in MCTS, and ensures a diverse
set of positions are encountered. For the remainder of the game, an infinitesimal
temperature is used, τ→0."

When comparing models, temperature should be 0

**Comment by barakugav** [comment]
4996bf51b236ca156561a4fb03fe27d58e2bb360
